### ISSUE TITLE
level one-off fixed in v0.50 not working in v0.53

### ISSUE THREAD

**Issue by marcelser** [mschout/Log-Log4perl-Layout-JSON#3] opened 2018-03-02 10:45 UTC
Hi,

We just upgraded our old Log-Log4perl-Layout-JSON-0.002003 to Log-Log4perl-Layout-JSON-0.53. I then removed my line:
`$Log::Log4perl::caller_depth = $Log::Log4perl::caller_depth + 1;`

Which I had to add after we started using the JSON Layout Appender v0.002003. Unfortunately after removing the line my log messages were still one off even with v0.53, so it seems that either the bug was supposedly fixed in v0.50 either isn't working or was re-introduced in a later version.

Can you please fix for v0.54?

**Comment by marcelser** [comment] 2018-03-02 10:58
I just checked the code of v0.53, the "caller_level++" in the render method is still there, nevertheless I still have to increase the caller level still by 1 after the init, so somehow this isn't solving the problem. Are we maybe in another subroutine call so the call stack is increased due to some changes in the Appender so that actually a +2 would be required?

**Comment by mschout** [comment] 2018-03-02 15:33
Hmm.. I'm unable to reproduce this.  I have 0.53 deployed in production and it logs the correct file/sub/line number for me.

Does the test suite pass for v0.53?  Because t/basic.t checks that the file that logged the message is correct.

e.g.:

        is_deeply $appender->string(), '{"category":"foo","class":"main","file":"basic.t","message":"info message","sub":"__ANON__"}'."\n";

How are you logging messages?  e.g.: are you doing something other than calling get_logger() and then using the standard log messages such as $logger->debug() etc?

If the test suite is passing, then I suspect something with how you are invoking log4perl as the issue.

**Comment by mschout** [comment] 2018-07-02 17:52
Closing, WORKSFORME.

**Closed by mschout** 2018-07-02 17:52 UTC
